### ISSUE TITLE
"Your platform doesn't support adaptive themes", but it does

### ISSUE THREAD

**Issue by fax1ty** [jpudysz/react-native-unistyles#264]
### Description

![image](https://github.com/user-attachments/assets/184e7358-70ce-4097-959b-2d599c376c01)

We encountered a startup crash on iOS. This happens occasionally. Sometimes the app starts, and sometimes it doesn't.

### Steps to reproduce

1. Run the app

### Unistyles version

2.8.4

### React Native version

0.74.2

### Platforms

iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey @fax1ty, version 2.8.0+ includes a new core with lazily loaded values, such as screen dimensions, insets, and color schemes. The error you're encountering indicates that no color scheme is detected on your platform. This may be due to a race condition where the Objective-C system callback is slower than the C++ logic.

This issue has been resolved in version 2.9.1. Please give it a try.

**Comment by jpudysz** [comment]
Anyway, I know that it might take some time to revalidate it on your side. So feel free to reopen if you will get the same behavior using version 2.9.1 (which is not likely to happen).
