### ISSUE TITLE
[V2] UNISTYLES_ERROR_RUNTIME_UNAVAILABLE

### ISSUE THREAD

**Issue by atanaskanchev** [jpudysz/react-native-unistyles#72]
### Description

Getting error `UNISTYLES_ERROR_RUNTIME_UNAVAILABLE` coming from `node_modules/react-native-unistyles/src/Unistyles.ts:18`

```ts
if (!isInstalled) {
            throw new Error(UnistylesError.RuntimeUnavailable)
}
```

### Steps to reproduce

![simulator_screenshot_06A84A8D-0F9A-47B3-B1F3-8D20ED8627BB](https://github.com/jpudysz/react-native-unistyles/assets/4958587/436cfce5-679b-41bf-960c-12728bdc7863)

### Snack or a link to a repository (optional)

https://github.com/atanaskanchev/rnu2

### Unistyles version

next

### React Native version

0.72.6

### Platforms

iOS

**Comment by jpudysz** [comment]
You need to `pod-install` :)

**Comment by atanaskanchev** [comment]
> You need to `pod-install` :)

So [I've tried](https://github.com/atanaskanchev/rnu2/commit/bc7cd475af1cbb4c2c71472927261d9fbe49a3c4):

1. `npx expo prebuild` and
2. installed the pods

but still getting the same

**Comment by jpudysz** [comment]
I think it's because v2 is not correctly configured for npm. I was only working on local copy. Let me check that 👌

**Comment by jpudysz** [comment]
@atanaskanchev please try with:

```
yarn add react-native-unistyles@next // 2.0.0-alpha.6
yarn expo prebuild --clean
```

**Comment by jpudysz** [comment]
Have you seen instructions from https://github.com/jpudysz/react-native-unistyles/discussions/41 ?
Android is not ready yet.

**Comment by atanaskanchev** [comment]
Ah, I'm sorry, I've missed the Android JSI wrapper task 😇. but I've followed the install instructions from there though

**Comment by atanaskanchev** [comment]
In the example config we've got 

```ts
type AppThemes = {
    light: typeof lightTheme
    dark: typeof darkTheme
    premium: typeof premiumTheme
}

declare module 'react-native-unistyles' {
    export interface UnistylesThemes extends AppThemes {}
```

Can an interface extend a type in TS, not sure?

**Comment by jpudysz** [comment]
I'm checking your repo, will get back soon

**Comment by jpudysz** [comment]
I was able to run the example:

<img width="335" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/0730d2b1-1782-42d5-8592-fe9040da0713">

I simply:

```sh
yarn
yarn expo prebuild
```

I'm getting TypeScript hints from the theme in `createStyleSheet`.

There is indeed issue with `theme` accessed from `useStyles` - I need to fix it in the next version.

<img width="693" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/402c28fc-0cae-4a68-92c9-f07af845f335">

I was able to run your example.

The problem is that you didn't import anywhere `/styles` folder so the UnistylesRegistry is not triggered. Your themes and breakpoints are empty.

To simply fix that add import:

```
import '../styles'
```
to the _layout.tsx, or import it somewhere else (some kind of index.ts file).

**Comment by atanaskanchev** [comment]
Unfortunately I'm still facing the issue after [updating to alpha 7 and importing the styles](https://github.com/atanaskanchev/rnu2/commit/f2810375d47305fcfdb3f1c472bfd8745054bfa5). Will close it down as most probably there's some issue with my local setup. Thanks for your help @jpudysz

**Comment by jpudysz** [comment]
Btw. I've just published alpha.8 with the fix for the `theme` hints:

![image](https://github.com/jpudysz/react-native-unistyles/assets/9088288/0e039b2d-2ccb-4faa-9ad8-d73db1fd6a4d)
